name: Update README with Blog Posts

on:
  schedule:
    - cron: '0 * * * *' # 매시간 실행
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1.3.0
        with:
          feed_list: "https://kimyih.github.io/feed.xml" # 블로그 RSS 피드 URL

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Updated blog posts' || exit 0
          git push
